// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Agent
 *
 * Agent model for storing chat agent prompts and metadata.
 *
 * Attributes:
 * id: The primary key
 * name: Name of the session (defaults to empty string)
 * created_at: When the session was created
 * messages: Relationship to session messages
 * user: Relationship to the session owner
 */
export type Agent = {
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name?: string;
    /**
     * Scenario Id
     */
    scenario_id: number;
    /**
     * Voice Id
     */
    voice_id?: number | null;
    /**
     * Display Text Color
     */
    display_text_color?: string;
    /**
     * Avatar Gcs Uri
     */
    avatar_gcs_uri?: string;
    /**
     * Objective
     */
    objective?: string;
    /**
     * Instructions
     */
    instructions?: string;
    /**
     * Constraints
     */
    constraints?: string;
    /**
     * Context
     */
    context?: string;
    /**
     * Agent Personality Id
     */
    agent_personality_id: number;
    /**
     * Owner Id
     */
    owner_id?: number | null;
};

/**
 * AgentCreate
 *
 * Request model for creating an agent.
 *
 * Attributes:
 * id: Agent ID (unique identifier)
 * name: Name of the agent
 * scenario_id: ID of the scenario this agent belongs to
 * agent_personality_id: ID of the agent's personality
 * voice: Voice identifier for TTS
 * display_text_color: Color for display
 * objective: Agent's objective
 * instructions: Agent's instructions
 * constraints: Agent's constraints
 * context: Agent's context
 */
export type AgentCreate = {
    /**
     * Id
     *
     * Agent ID (unique identifier)
     */
    id: string;
    /**
     * Name
     *
     * Name of the agent
     */
    name: string;
    /**
     * Scenario Id
     *
     * ID of the scenario this agent belongs to
     */
    scenario_id: number;
    /**
     * Agent Personality Id
     *
     * ID of the agent's personality
     */
    agent_personality_id: number;
    /**
     * Voice
     *
     * Voice identifier for TTS
     */
    voice?: string;
    /**
     * Display Text Color
     *
     * Color for display
     */
    display_text_color?: string;
    /**
     * Avatar Gcs Uri
     *
     * Avatar image file path
     */
    avatar_gcs_uri?: string;
    /**
     * Objective
     *
     * Agent's objective
     */
    objective?: string;
    /**
     * Instructions
     *
     * Agent's instructions
     */
    instructions?: string;
    /**
     * Constraints
     *
     * Agent's constraints
     */
    constraints?: string;
    /**
     * Context
     *
     * Agent's context
     */
    context?: string;
};

/**
 * AgentLlmConfigResponse
 *
 * Response model for an agent-to-LLM configuration.
 */
export type AgentLlmConfigResponse = {
    /**
     * Agent Type
     */
    agent_type: string;
    /**
     * Llm Model Id
     */
    llm_model_id: number;
    /**
     * Llm Model Name
     */
    llm_model_name: string;
};

/**
 * AgentLlmConfigUpdateRequest
 *
 * Request model for updating an agent-to-LLM configuration.
 */
export type AgentLlmConfigUpdateRequest = {
    /**
     * Agent Type
     */
    agent_type: string;
    /**
     * Llm Model Id
     */
    llm_model_id: number;
};

/**
 * AgentPersonality
 *
 * Database model for agent personality configurations.
 */
export type AgentPersonality = {
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Id
     */
    id?: number;
    /**
     * Name
     */
    name: string;
    /**
     * Personality Description
     */
    personality_description: string;
    /**
     * Owner Id
     */
    owner_id?: number | null;
};

/**
 * AgentPersonalityCreate
 *
 * Request model for creating an agent personality.
 *
 * Attributes:
 * name: Name of the personality
 * personality_description: Description of the personality traits
 */
export type AgentPersonalityCreate = {
    /**
     * Name
     *
     * Name of the personality
     */
    name: string;
    /**
     * Personality Description
     *
     * Description of the personality traits
     */
    personality_description: string;
};

/**
 * AgentPersonalityResponse
 *
 * Response model for agent personality operations.
 *
 * Attributes:
 * id: Personality ID
 * name: Name of the personality
 * personality_description: Description of the personality traits
 * created_at: When the personality was created
 * owner_id: Owner user ID (None means global)
 * is_global: Whether this is a global personality
 */
export type AgentPersonalityResponse = {
    /**
     * Id
     *
     * Personality ID
     */
    id: number;
    /**
     * Name
     *
     * Name of the personality
     */
    name: string;
    /**
     * Personality Description
     *
     * Description of the personality traits
     */
    personality_description: string;
    /**
     * Created At
     *
     * When the personality was created
     */
    created_at: string;
    /**
     * Owner Id
     *
     * Owner user ID (None means global)
     */
    owner_id?: number | null;
    /**
     * Is Global
     *
     * Whether this is a global personality
     */
    is_global?: boolean;
};

/**
 * AgentPersonalityUpdate
 *
 * Request model for updating an agent personality.
 *
 * Attributes:
 * name: Optional new name
 * personality_description: Optional new description
 */
export type AgentPersonalityUpdate = {
    /**
     * Name
     *
     * Name of the personality
     */
    name?: string | null;
    /**
     * Personality Description
     *
     * Description of the personality traits
     */
    personality_description?: string | null;
};

/**
 * AgentResponse
 *
 * Response model for agent operations.
 *
 * Attributes:
 * id: Agent ID
 * name: Name of the agent
 * scenario_id: ID of the scenario this agent belongs to
 * agent_personality_id: ID of the agent's personality
 * agent_personality: Optional agent personality object
 * voice: Voice identifier for TTS
 * display_text_color: Color for display
 * objective: Agent's objective
 * instructions: Agent's instructions
 * constraints: Agent's constraints
 * context: Agent's context
 * created_at: When the agent was created
 * owner_id: Owner user ID (None means global)
 * is_global: Whether this is a global agent
 */
export type AgentResponse = {
    /**
     * Id
     *
     * Agent ID
     */
    id: string;
    /**
     * Name
     *
     * Name of the agent
     */
    name: string;
    /**
     * Scenario Id
     *
     * ID of the scenario this agent belongs to
     */
    scenario_id: number;
    /**
     * Agent Personality Id
     *
     * ID of the agent's personality
     */
    agent_personality_id: number;
    /**
     * Agent personality object
     */
    agent_personality?: AgentPersonalityResponse | null;
    /**
     * Voice
     *
     * Voice identifier for TTS
     */
    voice: string;
    /**
     * Display Text Color
     *
     * Color for display
     */
    display_text_color: string;
    /**
     * Avatar Gcs Uri
     *
     * GCS URI for agent avatar image
     */
    avatar_gcs_uri?: string;
    /**
     * Objective
     *
     * Agent's objective
     */
    objective: string;
    /**
     * Instructions
     *
     * Agent's instructions
     */
    instructions: string;
    /**
     * Constraints
     *
     * Agent's constraints
     */
    constraints: string;
    /**
     * Context
     *
     * Agent's context
     */
    context: string;
    /**
     * Created At
     *
     * When the agent was created
     */
    created_at: string;
    /**
     * Owner Id
     *
     * Owner user ID (None means global)
     */
    owner_id?: number | null;
    /**
     * Is Global
     *
     * Whether this is a global agent
     */
    is_global?: boolean;
};

/**
 * AgentUpdate
 *
 * Request model for updating an agent.
 *
 * Attributes:
 * name: Optional new name
 * scenario_id: Optional new scenario ID
 * agent_personality_id: Optional new personality ID
 * voice: Optional new voice
 * display_text_color: Optional new display color
 * objective: Optional new objective
 * instructions: Optional new instructions
 * constraints: Optional new constraints
 * context: Optional new context
 */
export type AgentUpdate = {
    /**
     * Name
     *
     * Name of the agent
     */
    name?: string | null;
    /**
     * Scenario Id
     *
     * ID of the scenario this agent belongs to
     */
    scenario_id?: number | null;
    /**
     * Agent Personality Id
     *
     * ID of the agent's personality
     */
    agent_personality_id?: number | null;
    /**
     * Voice
     *
     * Voice identifier for TTS
     */
    voice?: string | null;
    /**
     * Display Text Color
     *
     * Color for display
     */
    display_text_color?: string | null;
    /**
     * Avatar Gcs Uri
     *
     * Avatar image file path
     */
    avatar_gcs_uri?: string | null;
    /**
     * Objective
     *
     * Agent's objective
     */
    objective?: string | null;
    /**
     * Instructions
     *
     * Agent's instructions
     */
    instructions?: string | null;
    /**
     * Constraints
     *
     * Agent's constraints
     */
    constraints?: string | null;
    /**
     * Context
     *
     * Agent's context
     */
    context?: string | null;
};

/**
 * AgentVoiceResponse
 *
 * Response model for agent voice.
 *
 * Attributes:
 * id: Voice ID
 * voice_name: Name of the voice
 */
export type AgentVoiceResponse = {
    /**
     * Id
     *
     * Voice ID
     */
    id: number;
    /**
     * Voice Name
     *
     * Name of the voice
     */
    voice_name: string;
};

/**
 * AvatarResponse
 *
 * Response model for avatars.
 */
export type AvatarResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * File Path
     */
    file_path: string;
};

/**
 * Body_login_api_v1_auth_login_post
 */
export type BodyLoginApiV1AuthLoginPost = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Grant Type
     */
    grant_type?: string;
};

/**
 * Body_update_session_name_api_v1_auth_session__session_id__name_patch
 */
export type BodyUpdateSessionNameApiV1AuthSessionSessionIdNamePatch = {
    /**
     * Name
     */
    name: string;
};

/**
 * ChatRequest
 *
 * Request model for chat endpoint.
 *
 * Attributes:
 * messages: List of messages in the conversation.
 * is_resumption: Whether the conversation is being resumed.
 * resumption_text: The text to resume the conversation.
 * audio_base64: Optional base64-encoded audio bytes for speech-to-text transcription.
 */
export type ChatRequest = {
    /**
     * Messages
     *
     * List of messages in the conversation
     */
    messages: Array<Message>;
    /**
     * Is Resumption
     *
     * Whether the conversation is being resumed
     */
    is_resumption?: boolean;
    /**
     * Resumption Text
     *
     * The text to resume the conversation
     */
    resumption_text?: string;
    /**
     * Audio Base64
     *
     * Optional base64-encoded audio bytes for speech-to-text transcription
     */
    audio_base64?: string | null;
};

/**
 * ChatResponse
 *
 * Response model for chat endpoint.
 *
 * Attributes:
 * messages: List of messages in the conversation.
 */
export type ChatResponse = {
    /**
     * Messages
     *
     * List of messages in the conversation
     */
    messages?: Array<Message>;
    /**
     * Interrupt Task
     *
     * The task to interrupt the conversation
     */
    interrupt_task?: string;
    /**
     * Interrupt Value
     *
     * The value to interrupt the conversation
     */
    interrupt_value?: string;
    /**
     * Interrupt Value Type
     *
     * The type of the interrupt value
     */
    interrupt_value_type?: 'text' | 'image' | 'audio' | 'video';
    /**
     * Student Responses
     *
     * List of student responses
     */
    student_responses?: Array<StudentResponse>;
    /**
     * Inline Feedback
     *
     * List of inline feedback
     */
    inline_feedback?: Array<string>;
    /**
     * Feedback Request Id
     *
     * ID to poll for async inline feedback if not immediately available
     */
    feedback_request_id?: string;
    /**
     * Summary Feedback
     *
     * The summary feedback for the student responses
     */
    summary_feedback?: SummaryFeedbackResponse | string;
    /**
     * Summary
     *
     * The summary of the student responses
     */
    summary?: string;
    /**
     * Answering Student
     *
     * The student number that is answering
     */
    answering_student?: number;
    /**
     * Appropriate Response
     *
     * Whether the response is appropriate
     */
    appropriate_response?: boolean;
    /**
     * Appropriate Explanation
     *
     * The explanation for why the response is appropriate
     */
    appropriate_explanation?: string;
    /**
     * Learning Goals Achieved
     *
     * Whether the learning goals were achieved
     */
    learning_goals_achieved?: boolean;
    /**
     * Transcribed Text
     *
     * The transcribed text from audio input
     */
    transcribed_text?: string;
    /**
     * Interrupt
     *
     * List of interrupts
     */
    interrupt?: Array<Interrupt>;
};

/**
 * DeleteAgentPersonalityResponse
 *
 * Response model for agent personality deletion.
 *
 * Attributes:
 * message: Success message
 */
export type DeleteAgentPersonalityResponse = {
    /**
     * Message
     *
     * Success message
     */
    message: string;
};

/**
 * DeleteAgentResponse
 *
 * Response model for agent deletion.
 *
 * Attributes:
 * message: Success message
 */
export type DeleteAgentResponse = {
    /**
     * Message
     *
     * Success message
     */
    message: string;
};

/**
 * DeleteFeedbackResponse
 *
 * Response model for feedback deletion.
 *
 * Attributes:
 * message: Success message
 */
export type DeleteFeedbackResponse = {
    /**
     * Message
     *
     * Success message
     */
    message: string;
};

/**
 * DeleteScenarioResponse
 *
 * Response model for scenario deletion.
 *
 * Attributes:
 * message: Success message
 */
export type DeleteScenarioResponse = {
    /**
     * Message
     *
     * Success message
     */
    message: string;
};

/**
 * DeleteUserResponse
 *
 * Response model for user deletion.
 *
 * Attributes:
 * message: The success message
 */
export type DeleteUserResponse = {
    /**
     * Message
     *
     * The success message
     */
    message: string;
};

/**
 * FeedbackCreate
 *
 * Request model for creating a feedback.
 *
 * Attributes:
 * feedback_type: Type of feedback ("inline" or "summary")
 * scenario_id: The scenario this feedback belongs to
 * objective: The objective of the feedback
 * instructions: The instructions for the feedback
 * constraints: The constraints for the feedback
 * context: The context for the feedback
 * output_format: The output format for the feedback (optional)
 */
export type FeedbackCreate = {
    /**
     * Type of feedback (inline or summary)
     */
    feedback_type: FeedbackType;
    /**
     * Scenario Id
     *
     * The scenario this feedback belongs to
     */
    scenario_id: number;
    /**
     * Objective
     *
     * The objective of the feedback
     */
    objective: string;
    /**
     * Instructions
     *
     * The instructions for the feedback
     */
    instructions: string;
    /**
     * Constraints
     *
     * The constraints for the feedback
     */
    constraints: string;
    /**
     * Context
     *
     * The context for the feedback
     */
    context: string;
    /**
     * Output Format
     *
     * The output format for the feedback
     */
    output_format?: string;
};

/**
 * FeedbackResponse
 *
 * Response model for feedback operations.
 *
 * Attributes:
 * id: Feedback ID
 * feedback_type: Type of feedback
 * scenario_id: The scenario this feedback belongs to
 * objective: The objective of the feedback
 * instructions: The instructions for the feedback
 * constraints: The constraints for the feedback
 * context: The context for the feedback
 * output_format: The output format for the feedback
 * created_at: When the feedback was created
 * owner_id: Owner user ID (None means global)
 * is_global: Whether this is global feedback
 */
export type FeedbackResponse = {
    /**
     * Id
     *
     * Feedback ID
     */
    id: number;
    /**
     * Type of feedback
     */
    feedback_type: FeedbackType;
    /**
     * Scenario Id
     *
     * The scenario this feedback belongs to
     */
    scenario_id: number;
    /**
     * Objective
     *
     * The objective of the feedback
     */
    objective: string;
    /**
     * Instructions
     *
     * The instructions for the feedback
     */
    instructions: string;
    /**
     * Constraints
     *
     * The constraints for the feedback
     */
    constraints: string;
    /**
     * Context
     *
     * The context for the feedback
     */
    context: string;
    /**
     * Output Format
     *
     * The output format for the feedback
     */
    output_format: string;
    /**
     * Created At
     *
     * When the feedback was created
     */
    created_at: string;
    /**
     * Owner Id
     *
     * Owner user ID (None means global)
     */
    owner_id?: number | null;
    /**
     * Is Global
     *
     * Whether this is global feedback
     */
    is_global?: boolean;
};

/**
 * FeedbackType
 *
 * Enumeration of feedback types.
 */
export type FeedbackType = 'inline' | 'summary';

/**
 * FeedbackUpdate
 *
 * Request model for updating a feedback.
 *
 * Attributes:
 * feedback_type: Optional new feedback type
 * scenario_id: Optional new scenario ID
 * objective: Optional new objective
 * instructions: Optional new instructions
 * constraints: Optional new constraints
 * context: Optional new context
 * output_format: Optional new output format
 */
export type FeedbackUpdate = {
    /**
     * Type of feedback (inline or summary)
     */
    feedback_type?: FeedbackType | null;
    /**
     * Scenario Id
     *
     * The scenario this feedback belongs to
     */
    scenario_id?: number | null;
    /**
     * Objective
     *
     * The objective of the feedback
     */
    objective?: string | null;
    /**
     * Instructions
     *
     * The instructions for the feedback
     */
    instructions?: string | null;
    /**
     * Constraints
     *
     * The constraints for the feedback
     */
    constraints?: string | null;
    /**
     * Context
     *
     * The context for the feedback
     */
    context?: string | null;
    /**
     * Output Format
     *
     * The output format for the feedback
     */
    output_format?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Interrupt
 */
export type Interrupt = {
    /**
     * Value
     */
    value: unknown;
    /**
     * Id
     */
    id: string;
};

/**
 * LlmModelResponse
 *
 * Response model for LLM models.
 */
export type LlmModelResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
};

/**
 * Message
 *
 * Message model for chat endpoint.
 *
 * Attributes:
 * role: The role of the message sender (user or assistant).
 * content: The content of the message.
 */
export type Message = {
    /**
     * Role
     *
     * The role of the message sender
     */
    role: 'user' | 'assistant' | 'system';
    /**
     * Content
     *
     * The content of the message
     */
    content: string;
};

/**
 * RegistrationResponse
 *
 * Response model for user registration.
 *
 * Attributes:
 * message: Success message
 * email: The registered email address
 */
export type RegistrationResponse = {
    /**
     * Message
     *
     * Success message
     */
    message: string;
    /**
     * Email
     *
     * The registered email address
     */
    email: string;
};

/**
 * Scenario
 *
 * Database model for scenario configurations.
 */
export type Scenario = {
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Id
     */
    id?: number;
    /**
     * Name
     */
    name?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Overview
     */
    overview?: string;
    /**
     * System Instructions
     */
    system_instructions?: string;
    /**
     * Initial Prompt
     */
    initial_prompt?: string;
    /**
     * Teaching Objectives
     */
    teaching_objectives?: string;
    /**
     * Owner Id
     */
    owner_id?: number | null;
};

/**
 * ScenarioAdminResponse
 *
 * Response model for scenario operations.
 *
 * Attributes:
 * id: Scenario ID
 * name: Name of the scenario
 * description: Description of the scenario
 * overview: Overview of the scenario
 * system_instructions: System instructions for the scenario
 * initial_prompt: Initial prompt for the scenario
 * teaching_objectives: Teaching objectives for the scenario
 * created_at: When the scenario was created
 * owner_id: Owner user ID (None means global)
 * is_global: Whether this is a global scenario
 */
export type ScenarioAdminResponse = {
    /**
     * Id
     *
     * Scenario ID
     */
    id: number;
    /**
     * Name
     *
     * Name of the scenario
     */
    name: string;
    /**
     * Description
     *
     * Description of the scenario
     */
    description: string;
    /**
     * Overview
     *
     * Overview of the scenario
     */
    overview: string;
    /**
     * System Instructions
     *
     * System instructions for the scenario
     */
    system_instructions: string;
    /**
     * Initial Prompt
     *
     * Initial prompt for the scenario
     */
    initial_prompt: string;
    /**
     * Teaching Objectives
     *
     * Teaching objectives for the scenario
     */
    teaching_objectives: string;
    /**
     * Created At
     *
     * When the scenario was created
     */
    created_at: string;
    /**
     * Owner Id
     *
     * Owner user ID (None means global)
     */
    owner_id?: number | null;
    /**
     * Is Global
     *
     * Whether this is a global scenario
     */
    is_global?: boolean;
};

/**
 * ScenarioCreateRequest
 *
 * Request model for creating a scenario.
 *
 * Attributes:
 * name: Name of the scenario
 * description: Description of the scenario
 * overview: Overview of the scenario
 * system_instructions: System instructions for the scenario
 * initial_prompt: Initial prompt for the scenario
 * teaching_objectives: Teaching objectives for the scenario
 */
export type ScenarioCreateRequest = {
    /**
     * Name
     *
     * Name of the scenario
     */
    name: string;
    /**
     * Description
     *
     * Description of the scenario
     */
    description: string;
    /**
     * Overview
     *
     * Overview of the scenario
     */
    overview: string;
    /**
     * System Instructions
     *
     * System instructions for the scenario
     */
    system_instructions: string;
    /**
     * Initial Prompt
     *
     * Initial prompt for the scenario
     */
    initial_prompt: string;
    /**
     * Teaching Objectives
     *
     * Teaching objectives for the scenario
     */
    teaching_objectives: string;
};

/**
 * ScenarioRequest
 *
 * Request model for scenario endpoint.
 *
 * Attributes:
 * scenario_id: The ID of the scenario to get.
 */
export type ScenarioRequest = {
    /**
     * Scenario Id
     *
     * The ID of the scenario to get
     */
    scenario_id?: number;
};

/**
 * ScenarioUpdateRequest
 *
 * Request model for updating a scenario.
 *
 * Attributes:
 * name: Optional new name
 * description: Optional new description
 * overview: Optional new overview
 * system_instructions: Optional new system instructions
 * initial_prompt: Optional new initial prompt
 * teaching_objectives: Optional new teaching objectives
 */
export type ScenarioUpdateRequest = {
    /**
     * Name
     *
     * Name of the scenario
     */
    name?: string | null;
    /**
     * Description
     *
     * Description of the scenario
     */
    description?: string | null;
    /**
     * Overview
     *
     * Overview of the scenario
     */
    overview?: string | null;
    /**
     * System Instructions
     *
     * System instructions for the scenario
     */
    system_instructions?: string | null;
    /**
     * Initial Prompt
     *
     * Initial prompt for the scenario
     */
    initial_prompt?: string | null;
    /**
     * Teaching Objectives
     *
     * Teaching objectives for the scenario
     */
    teaching_objectives?: string | null;
};

/**
 * ScenarioWithOwnerResponse
 *
 * Response model for scenario with ownership info (for scenario selection).
 *
 * Attributes:
 * id: Scenario ID
 * name: Name of the scenario
 * description: Description of the scenario
 * overview: Overview of the scenario
 * system_instructions: System instructions for the scenario
 * initial_prompt: Initial prompt for the scenario
 * teaching_objectives: Teaching objectives for the scenario
 * created_at: When the scenario was created
 * owner_id: Owner user ID (None means global)
 * is_global: Whether this is a global scenario
 */
export type ScenarioWithOwnerResponse = {
    /**
     * Id
     *
     * Scenario ID
     */
    id: number;
    /**
     * Name
     *
     * Name of the scenario
     */
    name: string;
    /**
     * Description
     *
     * Description of the scenario
     */
    description: string;
    /**
     * Overview
     *
     * Overview of the scenario
     */
    overview: string;
    /**
     * System Instructions
     *
     * System instructions for the scenario
     */
    system_instructions: string;
    /**
     * Initial Prompt
     *
     * Initial prompt for the scenario
     */
    initial_prompt: string;
    /**
     * Teaching Objectives
     *
     * Teaching objectives for the scenario
     */
    teaching_objectives: string;
    /**
     * Created At
     *
     * When the scenario was created
     */
    created_at?: string | null;
    /**
     * Owner Id
     *
     * Owner user ID (None means global)
     */
    owner_id?: number | null;
    /**
     * Is Global
     *
     * Whether this is a global scenario
     */
    is_global?: boolean;
};

/**
 * SessionListItem
 *
 * Response model for session list items (no token).
 */
export type SessionListItem = {
    /**
     * Session Id
     *
     * The unique identifier for the chat session
     */
    session_id: string;
    /**
     * Name
     *
     * Name of the session
     */
    name?: string;
};

/**
 * SessionResponse
 *
 * Response model for session creation.
 *
 * Attributes:
 * session_id: The unique identifier for the chat session
 * name: Name of the session (defaults to empty string)
 * token: The authentication token for the session
 */
export type SessionResponse = {
    /**
     * Session Id
     *
     * The unique identifier for the chat session
     */
    session_id: string;
    /**
     * Name
     *
     * Name of the session
     */
    name?: string;
    /**
     * The authentication token for the session
     */
    token: Token;
};

/**
 * StudentResponse
 *
 * Model for the student response.
 */
export type StudentResponse = {
    /**
     * Student Response
     *
     * The response from the student
     */
    student_response: string;
    student_details: Agent;
    student_personality: AgentPersonality;
    /**
     * Audio Base64
     *
     * Base64-encoded audio bytes for the student response
     */
    audio_base64?: string;
    /**
     * Audio Id
     *
     * Identifier for fetching audio lazily
     */
    audio_id?: string;
};

/**
 * SummaryFeedbackApiResponse
 *
 * Response model for summary feedback endpoint.
 */
export type SummaryFeedbackApiResponse = {
    /**
     * Summary Feedback
     */
    summary_feedback: SummaryFeedbackResponse | string;
};

/**
 * SummaryFeedbackRequest
 *
 * Request model for summary feedback endpoint.
 */
export type SummaryFeedbackRequest = {
    /**
     * Scenario Id
     */
    scenario_id: number;
    /**
     * Transcript
     */
    transcript: Array<TranscriptMessage>;
};

/**
 * SummaryFeedbackResponse
 *
 * Model for the summary feedback response.
 */
export type SummaryFeedbackResponse = {
    /**
     * Lesson Summary
     *
     * What happened in the lesson
     */
    lesson_summary: string;
    /**
     * Key Moments
     *
     * Two to three things they did excellent in the lesson
     */
    key_moments: string;
    /**
     * Overall Feedback
     *
     * Briefly describe how they did overall in the lesson
     */
    overall_feedback: string;
    /**
     * Your Strengths
     *
     * What they did well in the lesson
     */
    your_strengths: string;
    /**
     * Areas For Growth
     *
     * What they could improve in the lesson
     */
    areas_for_growth: string;
    /**
     * Next Steps
     *
     * What they should try next in the lesson to demonstrate the skill in the future
     */
    next_steps: string;
    /**
     * Celebration
     *
     * What they should celebrate in the lesson
     */
    celebration: string;
};

/**
 * Token
 *
 * Token model for authentication.
 *
 * Attributes:
 * access_token: The JWT access token.
 * token_type: The type of token (always "bearer").
 * expires_at: The token expiration timestamp.
 */
export type Token = {
    /**
     * Access Token
     *
     * The JWT access token
     */
    access_token: string;
    /**
     * Token Type
     *
     * The type of token
     */
    token_type?: string;
    /**
     * Expires At
     *
     * The token expiration timestamp
     */
    expires_at: string;
};

/**
 * TokenResponse
 *
 * Response model for login endpoint.
 *
 * Attributes:
 * access_token: The JWT access token
 * token_type: The type of token (always "bearer")
 * expires_at: When the token expires
 * is_admin: Whether the user is an admin
 */
export type TokenResponse = {
    /**
     * Access Token
     *
     * The JWT access token
     */
    access_token: string;
    /**
     * Token Type
     *
     * The type of token
     */
    token_type?: string;
    /**
     * Expires At
     *
     * When the token expires
     */
    expires_at: string;
    /**
     * Is Admin
     *
     * Whether the user is an admin
     */
    is_admin?: boolean;
};

/**
 * TranscriptMessage
 *
 * Message model for Gemini Live conversation transcript.
 */
export type TranscriptMessage = {
    /**
     * Role
     *
     * 'user' or 'agent'
     */
    role: string;
    /**
     * Text
     */
    text: string;
};

/**
 * UserCreate
 *
 * Request model for user registration.
 *
 * Attributes:
 * email: User's email address
 * password: User's password
 */
export type UserCreate = {
    /**
     * Email
     *
     * User's email address
     */
    email: string;
};

/**
 * UserResponse
 *
 * Response model for user operations.
 *
 * Attributes:
 * id: User's ID
 * email: User's email address
 * token: Authentication token
 * is_admin: Whether the user is an admin
 * is_approved: Whether the user's account has been approved
 * created_at: When the user was created
 */
export type UserResponse = {
    /**
     * Id
     *
     * User's ID
     */
    id: number;
    /**
     * Email
     *
     * User's email address
     */
    email: string;
    /**
     * Authentication token
     */
    token?: Token | null;
    /**
     * Is Admin
     *
     * Whether the user is an admin
     */
    is_admin?: boolean;
    /**
     * Is Approved
     *
     * Whether the user's account has been approved
     */
    is_approved?: boolean;
    /**
     * Created At
     *
     * When the user was created
     */
    created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * UserCreate
 *
 * Request model for user registration.
 *
 * Attributes:
 * email: User's email address
 * password: User's password
 */
export type UserCreateWritable = {
    /**
     * Email
     *
     * User's email address
     */
    email: string;
    /**
     * Password
     *
     * User's password
     */
    password: string;
};

export type RegisterApiV1AuthRegisterPostData = {
    body: UserCreateWritable;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterApiV1AuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiV1AuthRegisterPostError = RegisterApiV1AuthRegisterPostErrors[keyof RegisterApiV1AuthRegisterPostErrors];

export type RegisterApiV1AuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: RegistrationResponse;
};

export type RegisterApiV1AuthRegisterPostResponse = RegisterApiV1AuthRegisterPostResponses[keyof RegisterApiV1AuthRegisterPostResponses];

export type LoginApiV1AuthLoginPostData = {
    body: BodyLoginApiV1AuthLoginPost;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type CreateSessionApiV1AuthSessionPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/session';
};

export type CreateSessionApiV1AuthSessionPostResponses = {
    /**
     * Successful Response
     */
    200: SessionResponse;
};

export type CreateSessionApiV1AuthSessionPostResponse = CreateSessionApiV1AuthSessionPostResponses[keyof CreateSessionApiV1AuthSessionPostResponses];

export type UpdateSessionNameApiV1AuthSessionSessionIdNamePatchData = {
    body: BodyUpdateSessionNameApiV1AuthSessionSessionIdNamePatch;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/auth/session/{session_id}/name';
};

export type UpdateSessionNameApiV1AuthSessionSessionIdNamePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSessionNameApiV1AuthSessionSessionIdNamePatchError = UpdateSessionNameApiV1AuthSessionSessionIdNamePatchErrors[keyof UpdateSessionNameApiV1AuthSessionSessionIdNamePatchErrors];

export type UpdateSessionNameApiV1AuthSessionSessionIdNamePatchResponses = {
    /**
     * Successful Response
     */
    200: SessionResponse;
};

export type UpdateSessionNameApiV1AuthSessionSessionIdNamePatchResponse = UpdateSessionNameApiV1AuthSessionSessionIdNamePatchResponses[keyof UpdateSessionNameApiV1AuthSessionSessionIdNamePatchResponses];

export type DeleteSessionApiV1AuthSessionSessionIdDeleteData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/auth/session/{session_id}';
};

export type DeleteSessionApiV1AuthSessionSessionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSessionApiV1AuthSessionSessionIdDeleteError = DeleteSessionApiV1AuthSessionSessionIdDeleteErrors[keyof DeleteSessionApiV1AuthSessionSessionIdDeleteErrors];

export type DeleteSessionApiV1AuthSessionSessionIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUserSessionsApiV1AuthSessionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sessions';
};

export type GetUserSessionsApiV1AuthSessionsGetResponses = {
    /**
     * Response Get User Sessions Api V1 Auth Sessions Get
     *
     * Successful Response
     */
    200: Array<SessionListItem>;
};

export type GetUserSessionsApiV1AuthSessionsGetResponse = GetUserSessionsApiV1AuthSessionsGetResponses[keyof GetUserSessionsApiV1AuthSessionsGetResponses];

export type ChatApiV1ChatbotChatPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/chatbot/chat';
};

export type ChatApiV1ChatbotChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatApiV1ChatbotChatPostError = ChatApiV1ChatbotChatPostErrors[keyof ChatApiV1ChatbotChatPostErrors];

export type ChatApiV1ChatbotChatPostResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type ChatApiV1ChatbotChatPostResponse = ChatApiV1ChatbotChatPostResponses[keyof ChatApiV1ChatbotChatPostResponses];

export type ChatStreamApiV1ChatbotChatStreamPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/chatbot/chat/stream';
};

export type ChatStreamApiV1ChatbotChatStreamPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatStreamApiV1ChatbotChatStreamPostError = ChatStreamApiV1ChatbotChatStreamPostErrors[keyof ChatStreamApiV1ChatbotChatStreamPostErrors];

export type ChatStreamApiV1ChatbotChatStreamPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClearChatHistoryApiV1ChatbotMessagesDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/chatbot/messages';
};

export type ClearChatHistoryApiV1ChatbotMessagesDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSessionMessagesApiV1ChatbotMessagesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/chatbot/messages';
};

export type GetSessionMessagesApiV1ChatbotMessagesGetResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type GetSessionMessagesApiV1ChatbotMessagesGetResponse = GetSessionMessagesApiV1ChatbotMessagesGetResponses[keyof GetSessionMessagesApiV1ChatbotMessagesGetResponses];

export type GetFeedbackApiV1ChatbotFeedbackFeedbackIdGetData = {
    body?: never;
    path: {
        /**
         * Feedback Id
         */
        feedback_id: string;
    };
    query?: never;
    url: '/api/v1/chatbot/feedback/{feedback_id}';
};

export type GetFeedbackApiV1ChatbotFeedbackFeedbackIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFeedbackApiV1ChatbotFeedbackFeedbackIdGetError = GetFeedbackApiV1ChatbotFeedbackFeedbackIdGetErrors[keyof GetFeedbackApiV1ChatbotFeedbackFeedbackIdGetErrors];

export type GetFeedbackApiV1ChatbotFeedbackFeedbackIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSummaryFeedbackApiV1GeminiLiveSummaryFeedbackPostData = {
    body: SummaryFeedbackRequest;
    path?: never;
    query?: never;
    url: '/api/v1/gemini-live/summary-feedback';
};

export type GetSummaryFeedbackApiV1GeminiLiveSummaryFeedbackPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSummaryFeedbackApiV1GeminiLiveSummaryFeedbackPostError = GetSummaryFeedbackApiV1GeminiLiveSummaryFeedbackPostErrors[keyof GetSummaryFeedbackApiV1GeminiLiveSummaryFeedbackPostErrors];

export type GetSummaryFeedbackApiV1GeminiLiveSummaryFeedbackPostResponses = {
    /**
     * Successful Response
     */
    200: SummaryFeedbackApiResponse;
};

export type GetSummaryFeedbackApiV1GeminiLiveSummaryFeedbackPostResponse = GetSummaryFeedbackApiV1GeminiLiveSummaryFeedbackPostResponses[keyof GetSummaryFeedbackApiV1GeminiLiveSummaryFeedbackPostResponses];

export type GetAllScenariosApiV1ScenarioGetAllGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/scenario/get-all';
};

export type GetAllScenariosApiV1ScenarioGetAllGetResponses = {
    /**
     * Response Get All Scenarios Api V1 Scenario Get All Get
     *
     * Successful Response
     */
    200: Array<ScenarioWithOwnerResponse>;
};

export type GetAllScenariosApiV1ScenarioGetAllGetResponse = GetAllScenariosApiV1ScenarioGetAllGetResponses[keyof GetAllScenariosApiV1ScenarioGetAllGetResponses];

export type GetScenarioByIdApiV1ScenarioGetByIdScenarioIdGetData = {
    body?: never;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: number;
    };
    query?: never;
    url: '/api/v1/scenario/get-by-id/{scenario_id}';
};

export type GetScenarioByIdApiV1ScenarioGetByIdScenarioIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScenarioByIdApiV1ScenarioGetByIdScenarioIdGetError = GetScenarioByIdApiV1ScenarioGetByIdScenarioIdGetErrors[keyof GetScenarioByIdApiV1ScenarioGetByIdScenarioIdGetErrors];

export type GetScenarioByIdApiV1ScenarioGetByIdScenarioIdGetResponses = {
    /**
     * Successful Response
     */
    200: Scenario;
};

export type GetScenarioByIdApiV1ScenarioGetByIdScenarioIdGetResponse = GetScenarioByIdApiV1ScenarioGetByIdScenarioIdGetResponses[keyof GetScenarioByIdApiV1ScenarioGetByIdScenarioIdGetResponses];

export type SetCurrentScenarioByIdApiV1ScenarioSetCurrentByIdPostData = {
    body: ScenarioRequest;
    path?: never;
    query?: never;
    url: '/api/v1/scenario/set-current-by-id';
};

export type SetCurrentScenarioByIdApiV1ScenarioSetCurrentByIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetCurrentScenarioByIdApiV1ScenarioSetCurrentByIdPostError = SetCurrentScenarioByIdApiV1ScenarioSetCurrentByIdPostErrors[keyof SetCurrentScenarioByIdApiV1ScenarioSetCurrentByIdPostErrors];

export type SetCurrentScenarioByIdApiV1ScenarioSetCurrentByIdPostResponses = {
    /**
     * Successful Response
     */
    200: Scenario;
};

export type SetCurrentScenarioByIdApiV1ScenarioSetCurrentByIdPostResponse = SetCurrentScenarioByIdApiV1ScenarioSetCurrentByIdPostResponses[keyof SetCurrentScenarioByIdApiV1ScenarioSetCurrentByIdPostResponses];

export type GetScenarioAgentsApiV1ScenarioScenarioIdAgentsGetData = {
    body?: never;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: number;
    };
    query?: never;
    url: '/api/v1/scenario/{scenario_id}/agents';
};

export type GetScenarioAgentsApiV1ScenarioScenarioIdAgentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScenarioAgentsApiV1ScenarioScenarioIdAgentsGetError = GetScenarioAgentsApiV1ScenarioScenarioIdAgentsGetErrors[keyof GetScenarioAgentsApiV1ScenarioScenarioIdAgentsGetErrors];

export type GetScenarioAgentsApiV1ScenarioScenarioIdAgentsGetResponses = {
    /**
     * Response Get Scenario Agents Api V1 Scenario  Scenario Id  Agents Get
     *
     * Successful Response
     */
    200: Array<AgentResponse>;
};

export type GetScenarioAgentsApiV1ScenarioScenarioIdAgentsGetResponse = GetScenarioAgentsApiV1ScenarioScenarioIdAgentsGetResponses[keyof GetScenarioAgentsApiV1ScenarioScenarioIdAgentsGetResponses];

export type ListUsersApiV1AdminUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/users';
};

export type ListUsersApiV1AdminUsersGetResponses = {
    /**
     * Response List Users Api V1 Admin Users Get
     *
     * Successful Response
     */
    200: Array<UserResponse>;
};

export type ListUsersApiV1AdminUsersGetResponse = ListUsersApiV1AdminUsersGetResponses[keyof ListUsersApiV1AdminUsersGetResponses];

export type CreateUserApiV1AdminUsersPostData = {
    body: UserCreateWritable;
    path?: never;
    query?: never;
    url: '/api/v1/admin/users';
};

export type CreateUserApiV1AdminUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiV1AdminUsersPostError = CreateUserApiV1AdminUsersPostErrors[keyof CreateUserApiV1AdminUsersPostErrors];

export type CreateUserApiV1AdminUsersPostResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type CreateUserApiV1AdminUsersPostResponse = CreateUserApiV1AdminUsersPostResponses[keyof CreateUserApiV1AdminUsersPostResponses];

export type ListPendingUsersApiV1AdminUsersPendingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/users/pending';
};

export type ListPendingUsersApiV1AdminUsersPendingGetResponses = {
    /**
     * Response List Pending Users Api V1 Admin Users Pending Get
     *
     * Successful Response
     */
    200: Array<UserResponse>;
};

export type ListPendingUsersApiV1AdminUsersPendingGetResponse = ListPendingUsersApiV1AdminUsersPendingGetResponses[keyof ListPendingUsersApiV1AdminUsersPendingGetResponses];

export type DeleteUserApiV1AdminUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}';
};

export type DeleteUserApiV1AdminUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiV1AdminUsersUserIdDeleteError = DeleteUserApiV1AdminUsersUserIdDeleteErrors[keyof DeleteUserApiV1AdminUsersUserIdDeleteErrors];

export type DeleteUserApiV1AdminUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteUserResponse;
};

export type DeleteUserApiV1AdminUsersUserIdDeleteResponse = DeleteUserApiV1AdminUsersUserIdDeleteResponses[keyof DeleteUserApiV1AdminUsersUserIdDeleteResponses];

export type GetUserApiV1AdminUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}';
};

export type GetUserApiV1AdminUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserApiV1AdminUsersUserIdGetError = GetUserApiV1AdminUsersUserIdGetErrors[keyof GetUserApiV1AdminUsersUserIdGetErrors];

export type GetUserApiV1AdminUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetUserApiV1AdminUsersUserIdGetResponse = GetUserApiV1AdminUsersUserIdGetResponses[keyof GetUserApiV1AdminUsersUserIdGetResponses];

export type UpdateUserApiV1AdminUsersUserIdPutData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: {
        /**
         * Email
         */
        email?: string;
        /**
         * Is Admin
         */
        is_admin?: boolean;
    };
    url: '/api/v1/admin/users/{user_id}';
};

export type UpdateUserApiV1AdminUsersUserIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiV1AdminUsersUserIdPutError = UpdateUserApiV1AdminUsersUserIdPutErrors[keyof UpdateUserApiV1AdminUsersUserIdPutErrors];

export type UpdateUserApiV1AdminUsersUserIdPutResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type UpdateUserApiV1AdminUsersUserIdPutResponse = UpdateUserApiV1AdminUsersUserIdPutResponses[keyof UpdateUserApiV1AdminUsersUserIdPutResponses];

export type ApproveUserApiV1AdminUsersUserIdApprovePostData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}/approve';
};

export type ApproveUserApiV1AdminUsersUserIdApprovePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApproveUserApiV1AdminUsersUserIdApprovePostError = ApproveUserApiV1AdminUsersUserIdApprovePostErrors[keyof ApproveUserApiV1AdminUsersUserIdApprovePostErrors];

export type ApproveUserApiV1AdminUsersUserIdApprovePostResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type ApproveUserApiV1AdminUsersUserIdApprovePostResponse = ApproveUserApiV1AdminUsersUserIdApprovePostResponses[keyof ApproveUserApiV1AdminUsersUserIdApprovePostResponses];

export type RejectUserApiV1AdminUsersUserIdRejectPostData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/admin/users/{user_id}/reject';
};

export type RejectUserApiV1AdminUsersUserIdRejectPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RejectUserApiV1AdminUsersUserIdRejectPostError = RejectUserApiV1AdminUsersUserIdRejectPostErrors[keyof RejectUserApiV1AdminUsersUserIdRejectPostErrors];

export type RejectUserApiV1AdminUsersUserIdRejectPostResponses = {
    /**
     * Successful Response
     */
    200: DeleteUserResponse;
};

export type RejectUserApiV1AdminUsersUserIdRejectPostResponse = RejectUserApiV1AdminUsersUserIdRejectPostResponses[keyof RejectUserApiV1AdminUsersUserIdRejectPostResponses];

export type ListAgentPersonalitiesApiV1AdminAgentPersonalitiesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/agent-personalities';
};

export type ListAgentPersonalitiesApiV1AdminAgentPersonalitiesGetResponses = {
    /**
     * Response List Agent Personalities Api V1 Admin Agent Personalities Get
     *
     * Successful Response
     */
    200: Array<AgentPersonalityResponse>;
};

export type ListAgentPersonalitiesApiV1AdminAgentPersonalitiesGetResponse = ListAgentPersonalitiesApiV1AdminAgentPersonalitiesGetResponses[keyof ListAgentPersonalitiesApiV1AdminAgentPersonalitiesGetResponses];

export type CreateAgentPersonalityApiV1AdminAgentPersonalitiesPostData = {
    body: AgentPersonalityCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/agent-personalities';
};

export type CreateAgentPersonalityApiV1AdminAgentPersonalitiesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAgentPersonalityApiV1AdminAgentPersonalitiesPostError = CreateAgentPersonalityApiV1AdminAgentPersonalitiesPostErrors[keyof CreateAgentPersonalityApiV1AdminAgentPersonalitiesPostErrors];

export type CreateAgentPersonalityApiV1AdminAgentPersonalitiesPostResponses = {
    /**
     * Successful Response
     */
    200: AgentPersonalityResponse;
};

export type CreateAgentPersonalityApiV1AdminAgentPersonalitiesPostResponse = CreateAgentPersonalityApiV1AdminAgentPersonalitiesPostResponses[keyof CreateAgentPersonalityApiV1AdminAgentPersonalitiesPostResponses];

export type DeleteAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdDeleteData = {
    body?: never;
    path: {
        /**
         * Personality Id
         */
        personality_id: number;
    };
    query?: never;
    url: '/api/v1/admin/agent-personalities/{personality_id}';
};

export type DeleteAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdDeleteError = DeleteAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdDeleteErrors[keyof DeleteAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdDeleteErrors];

export type DeleteAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteAgentPersonalityResponse;
};

export type DeleteAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdDeleteResponse = DeleteAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdDeleteResponses[keyof DeleteAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdDeleteResponses];

export type GetAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdGetData = {
    body?: never;
    path: {
        /**
         * Personality Id
         */
        personality_id: number;
    };
    query?: never;
    url: '/api/v1/admin/agent-personalities/{personality_id}';
};

export type GetAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdGetError = GetAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdGetErrors[keyof GetAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdGetErrors];

export type GetAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdGetResponses = {
    /**
     * Successful Response
     */
    200: AgentPersonalityResponse;
};

export type GetAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdGetResponse = GetAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdGetResponses[keyof GetAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdGetResponses];

export type UpdateAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdPutData = {
    body: AgentPersonalityUpdate;
    path: {
        /**
         * Personality Id
         */
        personality_id: number;
    };
    query?: never;
    url: '/api/v1/admin/agent-personalities/{personality_id}';
};

export type UpdateAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdPutError = UpdateAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdPutErrors[keyof UpdateAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdPutErrors];

export type UpdateAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdPutResponses = {
    /**
     * Successful Response
     */
    200: AgentPersonalityResponse;
};

export type UpdateAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdPutResponse = UpdateAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdPutResponses[keyof UpdateAgentPersonalityApiV1AdminAgentPersonalitiesPersonalityIdPutResponses];

export type ListAgentsApiV1AdminAgentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/agents';
};

export type ListAgentsApiV1AdminAgentsGetResponses = {
    /**
     * Response List Agents Api V1 Admin Agents Get
     *
     * Successful Response
     */
    200: Array<AgentResponse>;
};

export type ListAgentsApiV1AdminAgentsGetResponse = ListAgentsApiV1AdminAgentsGetResponses[keyof ListAgentsApiV1AdminAgentsGetResponses];

export type CreateAgentApiV1AdminAgentsPostData = {
    body: AgentCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/agents';
};

export type CreateAgentApiV1AdminAgentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAgentApiV1AdminAgentsPostError = CreateAgentApiV1AdminAgentsPostErrors[keyof CreateAgentApiV1AdminAgentsPostErrors];

export type CreateAgentApiV1AdminAgentsPostResponses = {
    /**
     * Successful Response
     */
    200: AgentResponse;
};

export type CreateAgentApiV1AdminAgentsPostResponse = CreateAgentApiV1AdminAgentsPostResponses[keyof CreateAgentApiV1AdminAgentsPostResponses];

export type DeleteAgentApiV1AdminAgentsAgentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/v1/admin/agents/{agent_id}';
};

export type DeleteAgentApiV1AdminAgentsAgentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAgentApiV1AdminAgentsAgentIdDeleteError = DeleteAgentApiV1AdminAgentsAgentIdDeleteErrors[keyof DeleteAgentApiV1AdminAgentsAgentIdDeleteErrors];

export type DeleteAgentApiV1AdminAgentsAgentIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteAgentResponse;
};

export type DeleteAgentApiV1AdminAgentsAgentIdDeleteResponse = DeleteAgentApiV1AdminAgentsAgentIdDeleteResponses[keyof DeleteAgentApiV1AdminAgentsAgentIdDeleteResponses];

export type GetAgentApiV1AdminAgentsAgentIdGetData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/v1/admin/agents/{agent_id}';
};

export type GetAgentApiV1AdminAgentsAgentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAgentApiV1AdminAgentsAgentIdGetError = GetAgentApiV1AdminAgentsAgentIdGetErrors[keyof GetAgentApiV1AdminAgentsAgentIdGetErrors];

export type GetAgentApiV1AdminAgentsAgentIdGetResponses = {
    /**
     * Successful Response
     */
    200: AgentResponse;
};

export type GetAgentApiV1AdminAgentsAgentIdGetResponse = GetAgentApiV1AdminAgentsAgentIdGetResponses[keyof GetAgentApiV1AdminAgentsAgentIdGetResponses];

export type UpdateAgentApiV1AdminAgentsAgentIdPutData = {
    body: AgentUpdate;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/v1/admin/agents/{agent_id}';
};

export type UpdateAgentApiV1AdminAgentsAgentIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAgentApiV1AdminAgentsAgentIdPutError = UpdateAgentApiV1AdminAgentsAgentIdPutErrors[keyof UpdateAgentApiV1AdminAgentsAgentIdPutErrors];

export type UpdateAgentApiV1AdminAgentsAgentIdPutResponses = {
    /**
     * Successful Response
     */
    200: AgentResponse;
};

export type UpdateAgentApiV1AdminAgentsAgentIdPutResponse = UpdateAgentApiV1AdminAgentsAgentIdPutResponses[keyof UpdateAgentApiV1AdminAgentsAgentIdPutResponses];

export type ListScenariosApiV1AdminScenariosGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/scenarios';
};

export type ListScenariosApiV1AdminScenariosGetResponses = {
    /**
     * Response List Scenarios Api V1 Admin Scenarios Get
     *
     * Successful Response
     */
    200: Array<ScenarioAdminResponse>;
};

export type ListScenariosApiV1AdminScenariosGetResponse = ListScenariosApiV1AdminScenariosGetResponses[keyof ListScenariosApiV1AdminScenariosGetResponses];

export type CreateScenarioApiV1AdminScenariosPostData = {
    body: ScenarioCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/scenarios';
};

export type CreateScenarioApiV1AdminScenariosPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateScenarioApiV1AdminScenariosPostError = CreateScenarioApiV1AdminScenariosPostErrors[keyof CreateScenarioApiV1AdminScenariosPostErrors];

export type CreateScenarioApiV1AdminScenariosPostResponses = {
    /**
     * Successful Response
     */
    200: ScenarioAdminResponse;
};

export type CreateScenarioApiV1AdminScenariosPostResponse = CreateScenarioApiV1AdminScenariosPostResponses[keyof CreateScenarioApiV1AdminScenariosPostResponses];

export type DeleteScenarioApiV1AdminScenariosScenarioIdDeleteData = {
    body?: never;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: number;
    };
    query?: never;
    url: '/api/v1/admin/scenarios/{scenario_id}';
};

export type DeleteScenarioApiV1AdminScenariosScenarioIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteScenarioApiV1AdminScenariosScenarioIdDeleteError = DeleteScenarioApiV1AdminScenariosScenarioIdDeleteErrors[keyof DeleteScenarioApiV1AdminScenariosScenarioIdDeleteErrors];

export type DeleteScenarioApiV1AdminScenariosScenarioIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteScenarioResponse;
};

export type DeleteScenarioApiV1AdminScenariosScenarioIdDeleteResponse = DeleteScenarioApiV1AdminScenariosScenarioIdDeleteResponses[keyof DeleteScenarioApiV1AdminScenariosScenarioIdDeleteResponses];

export type GetScenarioApiV1AdminScenariosScenarioIdGetData = {
    body?: never;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: number;
    };
    query?: never;
    url: '/api/v1/admin/scenarios/{scenario_id}';
};

export type GetScenarioApiV1AdminScenariosScenarioIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScenarioApiV1AdminScenariosScenarioIdGetError = GetScenarioApiV1AdminScenariosScenarioIdGetErrors[keyof GetScenarioApiV1AdminScenariosScenarioIdGetErrors];

export type GetScenarioApiV1AdminScenariosScenarioIdGetResponses = {
    /**
     * Successful Response
     */
    200: ScenarioAdminResponse;
};

export type GetScenarioApiV1AdminScenariosScenarioIdGetResponse = GetScenarioApiV1AdminScenariosScenarioIdGetResponses[keyof GetScenarioApiV1AdminScenariosScenarioIdGetResponses];

export type UpdateScenarioApiV1AdminScenariosScenarioIdPutData = {
    body: ScenarioUpdateRequest;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: number;
    };
    query?: never;
    url: '/api/v1/admin/scenarios/{scenario_id}';
};

export type UpdateScenarioApiV1AdminScenariosScenarioIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateScenarioApiV1AdminScenariosScenarioIdPutError = UpdateScenarioApiV1AdminScenariosScenarioIdPutErrors[keyof UpdateScenarioApiV1AdminScenariosScenarioIdPutErrors];

export type UpdateScenarioApiV1AdminScenariosScenarioIdPutResponses = {
    /**
     * Successful Response
     */
    200: ScenarioAdminResponse;
};

export type UpdateScenarioApiV1AdminScenariosScenarioIdPutResponse = UpdateScenarioApiV1AdminScenariosScenarioIdPutResponses[keyof UpdateScenarioApiV1AdminScenariosScenarioIdPutResponses];

export type ListFeedbackApiV1AdminFeedbackGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/feedback';
};

export type ListFeedbackApiV1AdminFeedbackGetResponses = {
    /**
     * Response List Feedback Api V1 Admin Feedback Get
     *
     * Successful Response
     */
    200: Array<FeedbackResponse>;
};

export type ListFeedbackApiV1AdminFeedbackGetResponse = ListFeedbackApiV1AdminFeedbackGetResponses[keyof ListFeedbackApiV1AdminFeedbackGetResponses];

export type CreateFeedbackApiV1AdminFeedbackPostData = {
    body: FeedbackCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/feedback';
};

export type CreateFeedbackApiV1AdminFeedbackPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFeedbackApiV1AdminFeedbackPostError = CreateFeedbackApiV1AdminFeedbackPostErrors[keyof CreateFeedbackApiV1AdminFeedbackPostErrors];

export type CreateFeedbackApiV1AdminFeedbackPostResponses = {
    /**
     * Successful Response
     */
    200: FeedbackResponse;
};

export type CreateFeedbackApiV1AdminFeedbackPostResponse = CreateFeedbackApiV1AdminFeedbackPostResponses[keyof CreateFeedbackApiV1AdminFeedbackPostResponses];

export type DeleteFeedbackApiV1AdminFeedbackFeedbackIdDeleteData = {
    body?: never;
    path: {
        /**
         * Feedback Id
         */
        feedback_id: number;
    };
    query?: never;
    url: '/api/v1/admin/feedback/{feedback_id}';
};

export type DeleteFeedbackApiV1AdminFeedbackFeedbackIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFeedbackApiV1AdminFeedbackFeedbackIdDeleteError = DeleteFeedbackApiV1AdminFeedbackFeedbackIdDeleteErrors[keyof DeleteFeedbackApiV1AdminFeedbackFeedbackIdDeleteErrors];

export type DeleteFeedbackApiV1AdminFeedbackFeedbackIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteFeedbackResponse;
};

export type DeleteFeedbackApiV1AdminFeedbackFeedbackIdDeleteResponse = DeleteFeedbackApiV1AdminFeedbackFeedbackIdDeleteResponses[keyof DeleteFeedbackApiV1AdminFeedbackFeedbackIdDeleteResponses];

export type GetFeedbackApiV1AdminFeedbackFeedbackIdGetData = {
    body?: never;
    path: {
        /**
         * Feedback Id
         */
        feedback_id: number;
    };
    query?: never;
    url: '/api/v1/admin/feedback/{feedback_id}';
};

export type GetFeedbackApiV1AdminFeedbackFeedbackIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFeedbackApiV1AdminFeedbackFeedbackIdGetError = GetFeedbackApiV1AdminFeedbackFeedbackIdGetErrors[keyof GetFeedbackApiV1AdminFeedbackFeedbackIdGetErrors];

export type GetFeedbackApiV1AdminFeedbackFeedbackIdGetResponses = {
    /**
     * Successful Response
     */
    200: FeedbackResponse;
};

export type GetFeedbackApiV1AdminFeedbackFeedbackIdGetResponse = GetFeedbackApiV1AdminFeedbackFeedbackIdGetResponses[keyof GetFeedbackApiV1AdminFeedbackFeedbackIdGetResponses];

export type UpdateFeedbackApiV1AdminFeedbackFeedbackIdPutData = {
    body: FeedbackUpdate;
    path: {
        /**
         * Feedback Id
         */
        feedback_id: number;
    };
    query?: never;
    url: '/api/v1/admin/feedback/{feedback_id}';
};

export type UpdateFeedbackApiV1AdminFeedbackFeedbackIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateFeedbackApiV1AdminFeedbackFeedbackIdPutError = UpdateFeedbackApiV1AdminFeedbackFeedbackIdPutErrors[keyof UpdateFeedbackApiV1AdminFeedbackFeedbackIdPutErrors];

export type UpdateFeedbackApiV1AdminFeedbackFeedbackIdPutResponses = {
    /**
     * Successful Response
     */
    200: FeedbackResponse;
};

export type UpdateFeedbackApiV1AdminFeedbackFeedbackIdPutResponse = UpdateFeedbackApiV1AdminFeedbackFeedbackIdPutResponses[keyof UpdateFeedbackApiV1AdminFeedbackFeedbackIdPutResponses];

export type GetAgentVoicesApiV1UserContentAgentVoicesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user-content/agent-voices';
};

export type GetAgentVoicesApiV1UserContentAgentVoicesGetResponses = {
    /**
     * Response Get Agent Voices Api V1 User Content Agent Voices Get
     *
     * Successful Response
     */
    200: Array<AgentVoiceResponse>;
};

export type GetAgentVoicesApiV1UserContentAgentVoicesGetResponse = GetAgentVoicesApiV1UserContentAgentVoicesGetResponses[keyof GetAgentVoicesApiV1UserContentAgentVoicesGetResponses];

export type ListMyScenariosApiV1UserContentScenariosGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user-content/scenarios';
};

export type ListMyScenariosApiV1UserContentScenariosGetResponses = {
    /**
     * Response List My Scenarios Api V1 User Content Scenarios Get
     *
     * Successful Response
     */
    200: Array<ScenarioAdminResponse>;
};

export type ListMyScenariosApiV1UserContentScenariosGetResponse = ListMyScenariosApiV1UserContentScenariosGetResponses[keyof ListMyScenariosApiV1UserContentScenariosGetResponses];

export type CreateScenarioApiV1UserContentScenariosPostData = {
    body: ScenarioCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/user-content/scenarios';
};

export type CreateScenarioApiV1UserContentScenariosPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateScenarioApiV1UserContentScenariosPostError = CreateScenarioApiV1UserContentScenariosPostErrors[keyof CreateScenarioApiV1UserContentScenariosPostErrors];

export type CreateScenarioApiV1UserContentScenariosPostResponses = {
    /**
     * Successful Response
     */
    200: ScenarioAdminResponse;
};

export type CreateScenarioApiV1UserContentScenariosPostResponse = CreateScenarioApiV1UserContentScenariosPostResponses[keyof CreateScenarioApiV1UserContentScenariosPostResponses];

export type DeleteScenarioApiV1UserContentScenariosScenarioIdDeleteData = {
    body?: never;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: number;
    };
    query?: never;
    url: '/api/v1/user-content/scenarios/{scenario_id}';
};

export type DeleteScenarioApiV1UserContentScenariosScenarioIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteScenarioApiV1UserContentScenariosScenarioIdDeleteError = DeleteScenarioApiV1UserContentScenariosScenarioIdDeleteErrors[keyof DeleteScenarioApiV1UserContentScenariosScenarioIdDeleteErrors];

export type DeleteScenarioApiV1UserContentScenariosScenarioIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteScenarioResponse;
};

export type DeleteScenarioApiV1UserContentScenariosScenarioIdDeleteResponse = DeleteScenarioApiV1UserContentScenariosScenarioIdDeleteResponses[keyof DeleteScenarioApiV1UserContentScenariosScenarioIdDeleteResponses];

export type UpdateScenarioApiV1UserContentScenariosScenarioIdPutData = {
    body: ScenarioUpdateRequest;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: number;
    };
    query?: never;
    url: '/api/v1/user-content/scenarios/{scenario_id}';
};

export type UpdateScenarioApiV1UserContentScenariosScenarioIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateScenarioApiV1UserContentScenariosScenarioIdPutError = UpdateScenarioApiV1UserContentScenariosScenarioIdPutErrors[keyof UpdateScenarioApiV1UserContentScenariosScenarioIdPutErrors];

export type UpdateScenarioApiV1UserContentScenariosScenarioIdPutResponses = {
    /**
     * Successful Response
     */
    200: ScenarioAdminResponse;
};

export type UpdateScenarioApiV1UserContentScenariosScenarioIdPutResponse = UpdateScenarioApiV1UserContentScenariosScenarioIdPutResponses[keyof UpdateScenarioApiV1UserContentScenariosScenarioIdPutResponses];

export type CopyScenarioToLocalApiV1UserContentScenariosScenarioIdCopyPostData = {
    body?: never;
    path: {
        /**
         * Scenario Id
         */
        scenario_id: number;
    };
    query?: never;
    url: '/api/v1/user-content/scenarios/{scenario_id}/copy';
};

export type CopyScenarioToLocalApiV1UserContentScenariosScenarioIdCopyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CopyScenarioToLocalApiV1UserContentScenariosScenarioIdCopyPostError = CopyScenarioToLocalApiV1UserContentScenariosScenarioIdCopyPostErrors[keyof CopyScenarioToLocalApiV1UserContentScenariosScenarioIdCopyPostErrors];

export type CopyScenarioToLocalApiV1UserContentScenariosScenarioIdCopyPostResponses = {
    /**
     * Successful Response
     */
    200: ScenarioAdminResponse;
};

export type CopyScenarioToLocalApiV1UserContentScenariosScenarioIdCopyPostResponse = CopyScenarioToLocalApiV1UserContentScenariosScenarioIdCopyPostResponses[keyof CopyScenarioToLocalApiV1UserContentScenariosScenarioIdCopyPostResponses];

export type ListMyAgentPersonalitiesApiV1UserContentAgentPersonalitiesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user-content/agent-personalities';
};

export type ListMyAgentPersonalitiesApiV1UserContentAgentPersonalitiesGetResponses = {
    /**
     * Response List My Agent Personalities Api V1 User Content Agent Personalities Get
     *
     * Successful Response
     */
    200: Array<AgentPersonalityResponse>;
};

export type ListMyAgentPersonalitiesApiV1UserContentAgentPersonalitiesGetResponse = ListMyAgentPersonalitiesApiV1UserContentAgentPersonalitiesGetResponses[keyof ListMyAgentPersonalitiesApiV1UserContentAgentPersonalitiesGetResponses];

export type CreateAgentPersonalityApiV1UserContentAgentPersonalitiesPostData = {
    body: AgentPersonalityCreate;
    path?: never;
    query?: never;
    url: '/api/v1/user-content/agent-personalities';
};

export type CreateAgentPersonalityApiV1UserContentAgentPersonalitiesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAgentPersonalityApiV1UserContentAgentPersonalitiesPostError = CreateAgentPersonalityApiV1UserContentAgentPersonalitiesPostErrors[keyof CreateAgentPersonalityApiV1UserContentAgentPersonalitiesPostErrors];

export type CreateAgentPersonalityApiV1UserContentAgentPersonalitiesPostResponses = {
    /**
     * Successful Response
     */
    200: AgentPersonalityResponse;
};

export type CreateAgentPersonalityApiV1UserContentAgentPersonalitiesPostResponse = CreateAgentPersonalityApiV1UserContentAgentPersonalitiesPostResponses[keyof CreateAgentPersonalityApiV1UserContentAgentPersonalitiesPostResponses];

export type DeleteAgentPersonalityApiV1UserContentAgentPersonalitiesPersonalityIdDeleteData = {
    body?: never;
    path: {
        /**
         * Personality Id
         */
        personality_id: number;
    };
    query?: never;
    url: '/api/v1/user-content/agent-personalities/{personality_id}';
};

export type DeleteAgentPersonalityApiV1UserContentAgentPersonalitiesPersonalityIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAgentPersonalityApiV1UserContentAgentPersonalitiesPersonalityIdDeleteError = DeleteAgentPersonalityApiV1UserContentAgentPersonalitiesPersonalityIdDeleteErrors[keyof DeleteAgentPersonalityApiV1UserContentAgentPersonalitiesPersonalityIdDeleteErrors];

export type DeleteAgentPersonalityApiV1UserContentAgentPersonalitiesPersonalityIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteAgentPersonalityResponse;
};

export type DeleteAgentPersonalityApiV1UserContentAgentPersonalitiesPersonalityIdDeleteResponse = DeleteAgentPersonalityApiV1UserContentAgentPersonalitiesPersonalityIdDeleteResponses[keyof DeleteAgentPersonalityApiV1UserContentAgentPersonalitiesPersonalityIdDeleteResponses];

export type UpdateAgentPersonalityApiV1UserContentAgentPersonalitiesPersonalityIdPutData = {
    body: AgentPersonalityUpdate;
    path: {
        /**
         * Personality Id
         */
        personality_id: number;
    };
    query?: never;
    url: '/api/v1/user-content/agent-personalities/{personality_id}';
};

export type UpdateAgentPersonalityApiV1UserContentAgentPersonalitiesPersonalityIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAgentPersonalityApiV1UserContentAgentPersonalitiesPersonalityIdPutError = UpdateAgentPersonalityApiV1UserContentAgentPersonalitiesPersonalityIdPutErrors[keyof UpdateAgentPersonalityApiV1UserContentAgentPersonalitiesPersonalityIdPutErrors];

export type UpdateAgentPersonalityApiV1UserContentAgentPersonalitiesPersonalityIdPutResponses = {
    /**
     * Successful Response
     */
    200: AgentPersonalityResponse;
};

export type UpdateAgentPersonalityApiV1UserContentAgentPersonalitiesPersonalityIdPutResponse = UpdateAgentPersonalityApiV1UserContentAgentPersonalitiesPersonalityIdPutResponses[keyof UpdateAgentPersonalityApiV1UserContentAgentPersonalitiesPersonalityIdPutResponses];

export type CopyAgentPersonalityToLocalApiV1UserContentAgentPersonalitiesPersonalityIdCopyPostData = {
    body?: never;
    path: {
        /**
         * Personality Id
         */
        personality_id: number;
    };
    query?: never;
    url: '/api/v1/user-content/agent-personalities/{personality_id}/copy';
};

export type CopyAgentPersonalityToLocalApiV1UserContentAgentPersonalitiesPersonalityIdCopyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CopyAgentPersonalityToLocalApiV1UserContentAgentPersonalitiesPersonalityIdCopyPostError = CopyAgentPersonalityToLocalApiV1UserContentAgentPersonalitiesPersonalityIdCopyPostErrors[keyof CopyAgentPersonalityToLocalApiV1UserContentAgentPersonalitiesPersonalityIdCopyPostErrors];

export type CopyAgentPersonalityToLocalApiV1UserContentAgentPersonalitiesPersonalityIdCopyPostResponses = {
    /**
     * Successful Response
     */
    200: AgentPersonalityResponse;
};

export type CopyAgentPersonalityToLocalApiV1UserContentAgentPersonalitiesPersonalityIdCopyPostResponse = CopyAgentPersonalityToLocalApiV1UserContentAgentPersonalitiesPersonalityIdCopyPostResponses[keyof CopyAgentPersonalityToLocalApiV1UserContentAgentPersonalitiesPersonalityIdCopyPostResponses];

export type ListMyAgentsApiV1UserContentAgentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user-content/agents';
};

export type ListMyAgentsApiV1UserContentAgentsGetResponses = {
    /**
     * Response List My Agents Api V1 User Content Agents Get
     *
     * Successful Response
     */
    200: Array<AgentResponse>;
};

export type ListMyAgentsApiV1UserContentAgentsGetResponse = ListMyAgentsApiV1UserContentAgentsGetResponses[keyof ListMyAgentsApiV1UserContentAgentsGetResponses];

export type CreateAgentApiV1UserContentAgentsPostData = {
    body: AgentCreate;
    path?: never;
    query?: never;
    url: '/api/v1/user-content/agents';
};

export type CreateAgentApiV1UserContentAgentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAgentApiV1UserContentAgentsPostError = CreateAgentApiV1UserContentAgentsPostErrors[keyof CreateAgentApiV1UserContentAgentsPostErrors];

export type CreateAgentApiV1UserContentAgentsPostResponses = {
    /**
     * Successful Response
     */
    200: AgentResponse;
};

export type CreateAgentApiV1UserContentAgentsPostResponse = CreateAgentApiV1UserContentAgentsPostResponses[keyof CreateAgentApiV1UserContentAgentsPostResponses];

export type DeleteAgentApiV1UserContentAgentsAgentIdDeleteData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/v1/user-content/agents/{agent_id}';
};

export type DeleteAgentApiV1UserContentAgentsAgentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAgentApiV1UserContentAgentsAgentIdDeleteError = DeleteAgentApiV1UserContentAgentsAgentIdDeleteErrors[keyof DeleteAgentApiV1UserContentAgentsAgentIdDeleteErrors];

export type DeleteAgentApiV1UserContentAgentsAgentIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteAgentResponse;
};

export type DeleteAgentApiV1UserContentAgentsAgentIdDeleteResponse = DeleteAgentApiV1UserContentAgentsAgentIdDeleteResponses[keyof DeleteAgentApiV1UserContentAgentsAgentIdDeleteResponses];

export type UpdateAgentApiV1UserContentAgentsAgentIdPutData = {
    body: AgentUpdate;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/api/v1/user-content/agents/{agent_id}';
};

export type UpdateAgentApiV1UserContentAgentsAgentIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAgentApiV1UserContentAgentsAgentIdPutError = UpdateAgentApiV1UserContentAgentsAgentIdPutErrors[keyof UpdateAgentApiV1UserContentAgentsAgentIdPutErrors];

export type UpdateAgentApiV1UserContentAgentsAgentIdPutResponses = {
    /**
     * Successful Response
     */
    200: AgentResponse;
};

export type UpdateAgentApiV1UserContentAgentsAgentIdPutResponse = UpdateAgentApiV1UserContentAgentsAgentIdPutResponses[keyof UpdateAgentApiV1UserContentAgentsAgentIdPutResponses];

export type CopyAgentToLocalApiV1UserContentAgentsAgentIdCopyPostData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query: {
        /**
         * Target Scenario Id
         */
        target_scenario_id: number;
    };
    url: '/api/v1/user-content/agents/{agent_id}/copy';
};

export type CopyAgentToLocalApiV1UserContentAgentsAgentIdCopyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CopyAgentToLocalApiV1UserContentAgentsAgentIdCopyPostError = CopyAgentToLocalApiV1UserContentAgentsAgentIdCopyPostErrors[keyof CopyAgentToLocalApiV1UserContentAgentsAgentIdCopyPostErrors];

export type CopyAgentToLocalApiV1UserContentAgentsAgentIdCopyPostResponses = {
    /**
     * Successful Response
     */
    200: AgentResponse;
};

export type CopyAgentToLocalApiV1UserContentAgentsAgentIdCopyPostResponse = CopyAgentToLocalApiV1UserContentAgentsAgentIdCopyPostResponses[keyof CopyAgentToLocalApiV1UserContentAgentsAgentIdCopyPostResponses];

export type ListMyFeedbackApiV1UserContentFeedbackGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user-content/feedback';
};

export type ListMyFeedbackApiV1UserContentFeedbackGetResponses = {
    /**
     * Response List My Feedback Api V1 User Content Feedback Get
     *
     * Successful Response
     */
    200: Array<FeedbackResponse>;
};

export type ListMyFeedbackApiV1UserContentFeedbackGetResponse = ListMyFeedbackApiV1UserContentFeedbackGetResponses[keyof ListMyFeedbackApiV1UserContentFeedbackGetResponses];

export type CreateFeedbackApiV1UserContentFeedbackPostData = {
    body: FeedbackCreate;
    path?: never;
    query?: never;
    url: '/api/v1/user-content/feedback';
};

export type CreateFeedbackApiV1UserContentFeedbackPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFeedbackApiV1UserContentFeedbackPostError = CreateFeedbackApiV1UserContentFeedbackPostErrors[keyof CreateFeedbackApiV1UserContentFeedbackPostErrors];

export type CreateFeedbackApiV1UserContentFeedbackPostResponses = {
    /**
     * Successful Response
     */
    200: FeedbackResponse;
};

export type CreateFeedbackApiV1UserContentFeedbackPostResponse = CreateFeedbackApiV1UserContentFeedbackPostResponses[keyof CreateFeedbackApiV1UserContentFeedbackPostResponses];

export type DeleteFeedbackApiV1UserContentFeedbackFeedbackIdDeleteData = {
    body?: never;
    path: {
        /**
         * Feedback Id
         */
        feedback_id: number;
    };
    query?: never;
    url: '/api/v1/user-content/feedback/{feedback_id}';
};

export type DeleteFeedbackApiV1UserContentFeedbackFeedbackIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFeedbackApiV1UserContentFeedbackFeedbackIdDeleteError = DeleteFeedbackApiV1UserContentFeedbackFeedbackIdDeleteErrors[keyof DeleteFeedbackApiV1UserContentFeedbackFeedbackIdDeleteErrors];

export type DeleteFeedbackApiV1UserContentFeedbackFeedbackIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteFeedbackResponse;
};

export type DeleteFeedbackApiV1UserContentFeedbackFeedbackIdDeleteResponse = DeleteFeedbackApiV1UserContentFeedbackFeedbackIdDeleteResponses[keyof DeleteFeedbackApiV1UserContentFeedbackFeedbackIdDeleteResponses];

export type UpdateFeedbackApiV1UserContentFeedbackFeedbackIdPutData = {
    body: FeedbackUpdate;
    path: {
        /**
         * Feedback Id
         */
        feedback_id: number;
    };
    query?: never;
    url: '/api/v1/user-content/feedback/{feedback_id}';
};

export type UpdateFeedbackApiV1UserContentFeedbackFeedbackIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateFeedbackApiV1UserContentFeedbackFeedbackIdPutError = UpdateFeedbackApiV1UserContentFeedbackFeedbackIdPutErrors[keyof UpdateFeedbackApiV1UserContentFeedbackFeedbackIdPutErrors];

export type UpdateFeedbackApiV1UserContentFeedbackFeedbackIdPutResponses = {
    /**
     * Successful Response
     */
    200: FeedbackResponse;
};

export type UpdateFeedbackApiV1UserContentFeedbackFeedbackIdPutResponse = UpdateFeedbackApiV1UserContentFeedbackFeedbackIdPutResponses[keyof UpdateFeedbackApiV1UserContentFeedbackFeedbackIdPutResponses];

export type CopyFeedbackToLocalApiV1UserContentFeedbackFeedbackIdCopyPostData = {
    body?: never;
    path: {
        /**
         * Feedback Id
         */
        feedback_id: number;
    };
    query?: never;
    url: '/api/v1/user-content/feedback/{feedback_id}/copy';
};

export type CopyFeedbackToLocalApiV1UserContentFeedbackFeedbackIdCopyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CopyFeedbackToLocalApiV1UserContentFeedbackFeedbackIdCopyPostError = CopyFeedbackToLocalApiV1UserContentFeedbackFeedbackIdCopyPostErrors[keyof CopyFeedbackToLocalApiV1UserContentFeedbackFeedbackIdCopyPostErrors];

export type CopyFeedbackToLocalApiV1UserContentFeedbackFeedbackIdCopyPostResponses = {
    /**
     * Successful Response
     */
    200: FeedbackResponse;
};

export type CopyFeedbackToLocalApiV1UserContentFeedbackFeedbackIdCopyPostResponse = CopyFeedbackToLocalApiV1UserContentFeedbackFeedbackIdCopyPostResponses[keyof CopyFeedbackToLocalApiV1UserContentFeedbackFeedbackIdCopyPostResponses];

export type GetTtsAudioApiV1TtsAudioIdGetData = {
    body?: never;
    path: {
        /**
         * Audio Id
         */
        audio_id: string;
    };
    query?: never;
    url: '/api/v1/tts/{audio_id}';
};

export type GetTtsAudioApiV1TtsAudioIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTtsAudioApiV1TtsAudioIdGetError = GetTtsAudioApiV1TtsAudioIdGetErrors[keyof GetTtsAudioApiV1TtsAudioIdGetErrors];

export type GetTtsAudioApiV1TtsAudioIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetLlmModelsApiV1LlmModelsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/llm-models';
};

export type GetLlmModelsApiV1LlmModelsGetResponses = {
    /**
     * Response Get Llm Models Api V1 Llm Models Get
     *
     * Successful Response
     */
    200: Array<LlmModelResponse>;
};

export type GetLlmModelsApiV1LlmModelsGetResponse = GetLlmModelsApiV1LlmModelsGetResponses[keyof GetLlmModelsApiV1LlmModelsGetResponses];

export type GetAgentLlmConfigsApiV1LlmConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/llm-config';
};

export type GetAgentLlmConfigsApiV1LlmConfigGetResponses = {
    /**
     * Response Get Agent Llm Configs Api V1 Llm Config Get
     *
     * Successful Response
     */
    200: Array<AgentLlmConfigResponse>;
};

export type GetAgentLlmConfigsApiV1LlmConfigGetResponse = GetAgentLlmConfigsApiV1LlmConfigGetResponses[keyof GetAgentLlmConfigsApiV1LlmConfigGetResponses];

export type UpdateAgentLlmConfigApiV1LlmConfigPostData = {
    body: AgentLlmConfigUpdateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/llm-config';
};

export type UpdateAgentLlmConfigApiV1LlmConfigPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAgentLlmConfigApiV1LlmConfigPostError = UpdateAgentLlmConfigApiV1LlmConfigPostErrors[keyof UpdateAgentLlmConfigApiV1LlmConfigPostErrors];

export type UpdateAgentLlmConfigApiV1LlmConfigPostResponses = {
    /**
     * Successful Response
     */
    200: AgentLlmConfigResponse;
};

export type UpdateAgentLlmConfigApiV1LlmConfigPostResponse = UpdateAgentLlmConfigApiV1LlmConfigPostResponses[keyof UpdateAgentLlmConfigApiV1LlmConfigPostResponses];

export type GetAvatarsApiV1AvatarsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/avatars';
};

export type GetAvatarsApiV1AvatarsGetResponses = {
    /**
     * Response Get Avatars Api V1 Avatars Get
     *
     * Successful Response
     */
    200: Array<AvatarResponse>;
};

export type GetAvatarsApiV1AvatarsGetResponse = GetAvatarsApiV1AvatarsGetResponses[keyof GetAvatarsApiV1AvatarsGetResponses];

export type HealthCheckApiV1HealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthCheckApiV1HealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Response Health Check Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthCheckHealthGetResponse = HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];
